// <auto-generated />
using System;
using AgendaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaApi.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20250612131213_NewColumnInPurpose")]
    partial class NewColumnInPurpose
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaApi.Models.Log.LogActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Action");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Description");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ObjectId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Type");

                    b.Property<Guid>("User")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("User");

                    b.HasKey("Id");

                    b.HasIndex("User");

                    b.ToTable("LogActivity", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Access", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Access", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("IdPerson")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Person");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("IdPerson")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Person");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson")
                        .IsUnique();

                    b.HasIndex("IdRole");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Document");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FullName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Phone");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Secretary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Employee");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdEmployee")
                        .IsUnique();

                    b.ToTable("Secretary", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("IdAccess")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Access");

                    b.Property<Guid>("IdPerson")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Person");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("IdAccess");

                    b.HasIndex("IdPerson")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Schedule.Available", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("FinalTime")
                        .HasColumnType("datetime")
                        .HasColumnName("FinalTime");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Employee");

                    b.Property<Guid?>("IdScheduled")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Scheduled");

                    b.Property<DateTime>("InitialTime")
                        .HasColumnType("datetime")
                        .HasColumnName("InitialTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char")
                        .HasDefaultValue("A")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("FinalTime")
                        .IsUnique();

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdScheduled");

                    b.HasIndex("InitialTime")
                        .IsUnique();

                    b.ToTable("Available", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Schedule.Purpose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Description");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("DurationInMinutes");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Purpose", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Schedule.Scheduled", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("IdCustomer")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer");

                    b.Property<Guid>("IdPurpose")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Purpose");

                    b.Property<Guid>("IdSecretary")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Secretary");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdPurpose");

                    b.HasIndex("IdSecretary");

                    b.ToTable("Scheduled", (string)null);
                });

            modelBuilder.Entity("AgendaApi.Models.Log.LogActivity", b =>
                {
                    b.HasOne("AgendaApi.Models.Profiles.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LogActivity_User");

                    b.Navigation("FromUser");
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Customer", b =>
                {
                    b.HasOne("AgendaApi.Models.Profiles.Person", "FromPerson")
                        .WithOne()
                        .HasForeignKey("AgendaApi.Models.Profiles.Customer", "IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Customar_Person");

                    b.Navigation("FromPerson");
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Employee", b =>
                {
                    b.HasOne("AgendaApi.Models.Profiles.Person", "FromPerson")
                        .WithOne()
                        .HasForeignKey("AgendaApi.Models.Profiles.Employee", "IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Person");

                    b.HasOne("AgendaApi.Models.Profiles.Role", "FromRole")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Role");

                    b.Navigation("FromPerson");

                    b.Navigation("FromRole");
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.Secretary", b =>
                {
                    b.HasOne("AgendaApi.Models.Profiles.Person", "FromEmployee")
                        .WithOne()
                        .HasForeignKey("AgendaApi.Models.Profiles.Secretary", "IdEmployee")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Secretary_FromEmployee");

                    b.Navigation("FromEmployee");
                });

            modelBuilder.Entity("AgendaApi.Models.Profiles.User", b =>
                {
                    b.HasOne("AgendaApi.Models.Profiles.Access", "FromAccess")
                        .WithMany()
                        .HasForeignKey("IdAccess")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Access");

                    b.HasOne("AgendaApi.Models.Profiles.Person", "FromPerson")
                        .WithOne()
                        .HasForeignKey("AgendaApi.Models.Profiles.User", "IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_Person");

                    b.Navigation("FromAccess");

                    b.Navigation("FromPerson");
                });

            modelBuilder.Entity("AgendaApi.Models.Schedule.Available", b =>
                {
                    b.HasOne("AgendaApi.Models.Profiles.Employee", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Available_Employee");

                    b.HasOne("AgendaApi.Models.Schedule.Scheduled", "FromScheduled")
                        .WithMany()
                        .HasForeignKey("IdScheduled")
                        .HasConstraintName("FK_Available_Scheduled");

                    b.Navigation("FromEmployee");

                    b.Navigation("FromScheduled");
                });

            modelBuilder.Entity("AgendaApi.Models.Schedule.Purpose", b =>
                {
                    b.HasOne("AgendaApi.Models.Profiles.Role", "FromRole")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Purpose_FromRole");

                    b.Navigation("FromRole");
                });

            modelBuilder.Entity("AgendaApi.Models.Schedule.Scheduled", b =>
                {
                    b.HasOne("AgendaApi.Models.Profiles.Customer", "FromCustomer")
                        .WithMany()
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Scheduled_Customer");

                    b.HasOne("AgendaApi.Models.Schedule.Purpose", "FromPurpose")
                        .WithMany()
                        .HasForeignKey("IdPurpose")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Scheduled_Purpose");

                    b.HasOne("AgendaApi.Models.Profiles.Secretary", "FromSecretary")
                        .WithMany()
                        .HasForeignKey("IdSecretary")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Scheduled_Secretary");

                    b.Navigation("FromCustomer");

                    b.Navigation("FromPurpose");

                    b.Navigation("FromSecretary");
                });
#pragma warning restore 612, 618
        }
    }
}
